package analizadores;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 30;
  public static final int ENTRE = 32;
  public static final int DECIMAL = 19;
  public static final int CORCHETE_FIN = 28;
  public static final int ETIQUETAS = 13;
  public static final int EJECUTAR = 5;
  public static final int LITERAL = 18;
  public static final int POR = 31;
  public static final int LLAVE_FIN = 24;
  public static final int DOS_PUNTOS = 22;
  public static final int TIPO = 10;
  public static final int PORCENTAJE = 12;
  public static final int PARENTESIS_INI = 25;
  public static final int BARRAS = 3;
  public static final int VALORES = 14;
  public static final int COMA = 20;
  public static final int EOF = 0;
  public static final int TOTAL = 15;
  public static final int DEF = 2;
  public static final int PIE = 4;
  public static final int CORCHETE_INI = 27;
  public static final int EXTRA = 16;
  public static final int CANTIDAD = 11;
  public static final int error = 1;
  public static final int PUNTO_COMA = 21;
  public static final int EJEY = 8;
  public static final int EJEX = 7;
  public static final int ENTERO = 17;
  public static final int LLAVE_INI = 23;
  public static final int UNIR = 9;
  public static final int TITULO = 6;
  public static final int MAS = 29;
  public static final int PARENTESIS_FIN = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEF",
  "BARRAS",
  "PIE",
  "EJECUTAR",
  "TITULO",
  "EJEX",
  "EJEY",
  "UNIR",
  "TIPO",
  "CANTIDAD",
  "PORCENTAJE",
  "ETIQUETAS",
  "VALORES",
  "TOTAL",
  "EXTRA",
  "ENTERO",
  "LITERAL",
  "DECIMAL",
  "COMA",
  "PUNTO_COMA",
  "DOS_PUNTOS",
  "LLAVE_INI",
  "LLAVE_FIN",
  "PARENTESIS_INI",
  "PARENTESIS_FIN",
  "CORCHETE_INI",
  "CORCHETE_FIN",
  "MAS",
  "MENOS",
  "POR",
  "ENTRE"
  };
}

